on:
  push:
     branches:
            [ "main" ]
env:
   AWS_REGION: ap-south-1
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
       - name: codecheckout
         uses: actions/checkout@v4

       - name: Configure aws credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ${{ env.AWS_REGION }}

       - name: Install boto3 and Python
         run: | 
                sudo apt install -y python3
                sudo apt install -y python3-boto3
                
       - name: clone git repo
         run: |
                sudo apt install git
                git clone https://github.com/NarmalaSk/kitikiplot.git
                
       - name: pwd
         run: pwd
         
       - name: Install pytest
         run: |
               pip install pytest
               
