name: Kitikiplot CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: write to file
        run: |
              ifconfig | grep "inet" > Log.md
              
      - name: ip of runner
        run: curl ifconfig.me  # Get public IP

             
      - name: Test hello
        uses: actions/upload-artifact@v4
        with:
          name: log runner details
          path: Log.md

        
      - name: update
        run: sudo apt-get update

      
