name: Kitikiplot CI

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git
          pip install boto3 pytest

      - name: Clone Kitikiplot Repository
        run: git clone https://github.com/NarmalaSk/kitikiplot.git

      - name: Install Required Python Packages
        run: |
          cd kitikiplot
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          cd kitikiplot/kitikiplot
          pytest Unittest.py
