name: Kitikiplot CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git flake8
          pip install boto3 pytest


      - name: Install Required Python Packages
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          cd kitikiplot
          pytest Unittest.py

      
