name: Cicd to push s3 bucket into S3 bucket
on:
  push:
     branches:
      - main 
jobs:
 build:
   runs-on: ubuntu-latest

   steps: 
     - name: codecheckout
       uses: actions/checkout@v4.2.2

     - name: Install libraries
       run: |
             sudo apt-get install python awscli2 npm 
             pip install boto3

     - name: Build Docsauraus project
       run: |
             cd cloudkodes
             npm run build

      
             
     
             
   
   
