name: Cicd to push s3 bucket into S3 bucket
on:
  push:
     branches:
      - main 
jobs:
 build:
   runs-on: ubuntu-latest

   steps: 
     - name: codecheckout
       uses: actions/checkout@v4.2.2

     - name: Install libraries
       run: |
             sudo apt update && sudo apt install -y python3 python3-pip unzip npm 
             curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install --update
             pip install boto3
             npx create-docusaurus@latest my-website classic

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
        aws-region: ap-south-1

      
     - name: Push static site to S3 Bucket
       run: aws s3 sync cloudkodes/build s3://cloudkodes
     
             
   
   
